apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-read
  name: redis-read
  namespace: k8s-example
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
